  services:
  nextjs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - /app/node_modules